// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARYbLuNqL-Rg35YjG7LoMPEuoXxBHpa70',
    appId: '1:549441686831:web:e5ca9048045cd95dd8a5da',
    messagingSenderId: '549441686831',
    projectId: 'nouvellegeneration-2b616',
    authDomain: 'nouvellegeneration-2b616.firebaseapp.com',
    storageBucket: 'nouvellegeneration-2b616.appspot.com',
    measurementId: 'G-EHCE283YXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDo2Bpt7Wv6vETOcWp1cpBvYfRzwm997CQ',
    appId: '1:549441686831:android:9d06dbbc87c99131d8a5da',
    messagingSenderId: '549441686831',
    projectId: 'nouvellegeneration-2b616',
    storageBucket: 'nouvellegeneration-2b616.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq61Ggg9OdCQ3EzuRBNuJi-krvj62hhfY',
    appId: '1:549441686831:ios:f08fd7b4dddc9845d8a5da',
    messagingSenderId: '549441686831',
    projectId: 'nouvellegeneration-2b616',
    storageBucket: 'nouvellegeneration-2b616.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq61Ggg9OdCQ3EzuRBNuJi-krvj62hhfY',
    appId: '1:549441686831:ios:f08fd7b4dddc9845d8a5da',
    messagingSenderId: '549441686831',
    projectId: 'nouvellegeneration-2b616',
    storageBucket: 'nouvellegeneration-2b616.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARYbLuNqL-Rg35YjG7LoMPEuoXxBHpa70',
    appId: '1:549441686831:web:84c379846f8a3f80d8a5da',
    messagingSenderId: '549441686831',
    projectId: 'nouvellegeneration-2b616',
    authDomain: 'nouvellegeneration-2b616.firebaseapp.com',
    storageBucket: 'nouvellegeneration-2b616.appspot.com',
    measurementId: 'G-80KL9RJDBJ',
  );
}
